teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [ 4 ]
    axis_mappings:
      - axis: 3
        target: angular.z
      - axis: 1
        target: linear.x
      - axis: 0
        target: linear.y
