PointfootCTSVisionCfg:
  joint_names:
    - "abad_L_Joint"
    - "abad_R_Joint"
    - "hip_L_Joint"
    - "hip_R_Joint"
    - "knee_L_Joint"
    - "knee_R_Joint"

  init_state:
    # target angles [rad] when action = 0.0
    default_joint_angle:
      abad_L_Joint: 0.0
      hip_L_Joint: 0.0
      knee_L_Joint: 0.0

      abad_R_Joint: 0.0
      hip_R_Joint: 0.0
      knee_R_Joint: 0.0

  control:
    # PD Drive parameters:
    stiffness: 40.0
    damping: 2.5
    action_scale_pos: 0.25
    decimation: 10
    user_torque_limit: 80

  normalization:
    clip_scales:
      clip_observations: 100.
      clip_actions: 100.

  depth_image:
    original: [ 480, 848 ]
    resized: [ 60, 106 ] # [height, width]
    near_clip: 0.05
    far_clip: 5.0
    horizontal_fov: 87
    buffer_len: 2
  
  size:
    actions_size: 6
    observations_size: 32
    commands_size: 3
    obs_history_length: 5
    hidden_state_size: 512
    hm_latent_dim: 512
    ep_latent_dim: 128

  stand_mode:
    stand_duration: 1.0

  imu_orientation_offset:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
