controllers:
  pointfoot_controller:
    type: robot_controller/PointfootController
  pointfoot_vision_controller:
    type: robot_controller/PointfootVisionController
  pointfoot_cts_vision_controller:
    type: robot_controller/PointfootCTSVisionController
